In [4]:
#introduction to pandas
import pandas as pd
df=pd.read_csv("C:/Users/jasme/OneDrive/Desktop/data.csv.csv")
print(df.head(1000))

     Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0    2023                     Level 1                99999
1    2023                     Level 1                99999
2    2023                     Level 1                99999
3    2023                     Level 1                99999
4    2023                     Level 1                99999
..    ...                         ...                  ...
995  2023                     Level 3                 CC52
996  2023                     Level 3                 CC52
997  2023                     Level 3                 CC52
998  2023                     Level 4                CC521
999  2023                     Level 4                CC521

                                  Industry_name_NZSIOC               Units  \
0                                       All industries  Dollars (millions)
1                                       All industries  Dollars (millions)
2                                       All industries  Dollars (millions)
3                                       All industries  Dollars (millions)
4                                       All industries  Dollars (millions)
..                                                 ...                 ...
995  Basic Chemical and Chemical Product Manufacturing          Percentage
996  Basic Chemical and Chemical Product Manufacturing          Percentage
997  Basic Chemical and Chemical Product Manufacturing          Percentage
998     Basic Chemical and Basic Polymer Manufacturing  Dollars (millions)
999     Basic Chemical and Basic Polymer Manufacturing  Dollars (millions)

    Variable_code                                    Variable_name  \
0             H01                                     Total income
1             H04  Sales, government funding, grants and subsidies
2             H05                Interest, dividends and donations
3             H07                             Non-operating income
4             H08                                Total expenditure
..            ...                                              ...
995           H39                                 Return on equity
996           H40                           Return on total assets
997           H41                            Liabilities structure
998           H01                                     Total income
999           H04                      Sales of goods and services

         Variable_category   Value  \
0    Financial performance  930995
1    Financial performance  821630
2    Financial performance   84354
3    Financial performance   25010
4    Financial performance  832964
..                     ...     ...
995       Financial ratios      11
996       Financial ratios       5
997       Financial ratios      46
998  Financial performance    2062
999  Financial performance       C

                                Industry_code_ANZSIC06
0    ANZSIC06 divisions A-S (excluding classes K633...
1    ANZSIC06 divisions A-S (excluding classes K633...
2    ANZSIC06 divisions A-S (excluding classes K633...
3    ANZSIC06 divisions A-S (excluding classes K633...
4    ANZSIC06 divisions A-S (excluding classes K633...
..                                                 ...
995  ANZSIC06 groups C181, C182, C183, C184, C185, ...
996  ANZSIC06 groups C181, C182, C183, C184, C185, ...
997  ANZSIC06 groups C181, C182, C183, C184, C185, ...
998                      ANZSIC06 groups C181 and C182
999                      ANZSIC06 groups C181 and C182

[1000 rows x 10 columns]

In [5]:
#creating dataframe from a dictionary
import pandas as pd
data_set={
    'car_name':['BMW','AUDI','FORD'],
    'passing':[3,7,2]
}

df=pd.DataFrame(data_set)
print(df)

  car_name  passing
0      BMW        3
1     AUDI        7
2     FORD        2

In [9]:
#creating series from a list

import pandas as pd 
l=[1,2,3,4,5,6,7,8,9,10]

df=pd.Series(l)
print(df)
#fetching 1st value of a series

print('First value of a series:',df[0])

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
First value of a series: 1

In [12]:
#creating series from a list and giving your own indexes 

import pandas as pd
l=[1,2,3]

df=pd.Series(l,index=['a','b','c'])

print(df)

#return the value of index b

print('Value of index is :',df['b'])

a    1
b    2
c    3
dtype: int64
Value of index is : 2

In [13]:
#creating series from a dictionary

import pandas as pd

dict={'day1':400,'day2':450,'day3':500}

s=pd.Series(dict)
print(s)

day1    400
day2    450
day3    500
dtype: int64

In [15]:
#creating series from a dictionary and also passing the index

import pandas as pd

dict={'day1':400,'day2':450,'day3':500}

s=pd.Series(dict,index=['day1','day2'])
print(s)

day1    400
day2    450
dtype: int64

In [26]:
#creating dataframe from a dictionary and also passing the index

import pandas as pd

dict={'subject':['English','Hindi','Maths','Science','Social Sciene'],
      'Score':[85,70,95,95,95]
     }

df=pd.DataFrame(dict)
print(df)
print(df.loc[[0,1]])
print(df['subject'])
print(df.iloc[[0,1]])

         subject  Score
0        English     85
1          Hindi     70
2          Maths     95
3        Science     95
4  Social Sciene     95
   subject  Score
0  English     85
1    Hindi     70
0          English
1            Hindi
2            Maths
3          Science
4    Social Sciene
Name: subject, dtype: object
   subject  Score
0  English     85
1    Hindi     70

In [27]:
#introduction to pandas
import pandas as pd
pd.options.display.max_rows = 999
df=pd.read_csv("C:/Users/jasme/OneDrive/Desktop/data.csv.csv")
print(df)

       Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2023                     Level 1                99999
1      2023                     Level 1                99999
2      2023                     Level 1                99999
3      2023                     Level 1                99999
4      2023                     Level 1                99999
...     ...                         ...                  ...
50980  2013                     Level 3                 ZZ11
50981  2013                     Level 3                 ZZ11
50982  2013                     Level 3                 ZZ11
50983  2013                     Level 3                 ZZ11
50984  2013                     Level 3                 ZZ11

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01
1                  All industries  Dollars (millions)           H04
2                  All industries  Dollars (millions)           H05
3                  All industries  Dollars (millions)           H07
4                  All industries  Dollars (millions)           H08
...                           ...                 ...           ...
50980  Food product manufacturing          Percentage           H37
50981  Food product manufacturing          Percentage           H38
50982  Food product manufacturing          Percentage           H39
50983  Food product manufacturing          Percentage           H40
50984  Food product manufacturing          Percentage           H41

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance
1      Sales, government funding, grants and subsidies  Financial performance
2                    Interest, dividends and donations  Financial performance
3                                 Non-operating income  Financial performance
4                                    Total expenditure  Financial performance
...                                                ...                    ...
50980                                      Quick ratio       Financial ratios
50981              Margin on sales of goods for resale       Financial ratios
50982                                 Return on equity       Financial ratios
50983                           Return on total assets       Financial ratios
50984                            Liabilities structure       Financial ratios

        Value                             Industry_code_ANZSIC06
0      930995  ANZSIC06 divisions A-S (excluding classes K633...
1      821630  ANZSIC06 divisions A-S (excluding classes K633...
2       84354  ANZSIC06 divisions A-S (excluding classes K633...
3       25010  ANZSIC06 divisions A-S (excluding classes K633...
4      832964  ANZSIC06 divisions A-S (excluding classes K633...
...       ...                                                ...
50980      52  ANZSIC06 groups C111, C112, C113, C114, C115, ...
50981      40  ANZSIC06 groups C111, C112, C113, C114, C115, ...
50982      12  ANZSIC06 groups C111, C112, C113, C114, C115, ...
50983       5  ANZSIC06 groups C111, C112, C113, C114, C115, ...
50984      46  ANZSIC06 groups C111, C112, C113, C114, C115, ...

[50985 rows x 10 columns]

In [36]:
#creating a dataframe from a dictionary

import pandas as pd
data={
    'Duration':{
        '0':60,
        '1':60,
        '2':45,
        '3':45,
        '4':60,
        '5':60,
        '6':75,
        '7':45,
        '8':45,
        '9':62
        
    },
    'pulse':{
        '0':110,
        '1':113,
        '2':116,
        '3':100,
        '4':70,
        '5':110,
        '6':113,
        '7':116,
        '8':100,
        '9':70
    },
    'max_pulse':{
        '0':130,
        '1':133,
        '2':136,
        '3':120,
        '4':90,
        '5':130,
        '6':133,
        '7':136,
        '8':120,
        '9':90
    }
    
}

df=pd.DataFrame(data)
print(df)

print('First 10 rows of a dataframe')
print(df.head(10))

print('First 5 rows of a dataframe')
print(df.head())

print('Last 5 rows of a dataframe')
print(df.tail())

print('Last 10 rows of a dataframe')
print(df.tail(10))

print('Dataframe info')
print(df.info())

   Duration  pulse  max_pulse
0        60    110        130
1        60    113        133
2        45    116        136
3        45    100        120
4        60     70         90
5        60    110        130
6        75    113        133
7        45    116        136
8        45    100        120
9        62     70         90
First 10 rows of a dataframe
   Duration  pulse  max_pulse
0        60    110        130
1        60    113        133
2        45    116        136
3        45    100        120
4        60     70         90
5        60    110        130
6        75    113        133
7        45    116        136
8        45    100        120
9        62     70         90
First 5 rows of a dataframe
   Duration  pulse  max_pulse
0        60    110        130
1        60    113        133
2        45    116        136
3        45    100        120
4        60     70         90
Last 5 rows of a dataframe
   Duration  pulse  max_pulse
5        60    110        130
6        75    113        133
7        45    116        136
8        45    100        120
9        62     70         90
Last 10 rows of a dataframe
   Duration  pulse  max_pulse
0        60    110        130
1        60    113        133
2        45    116        136
3        45    100        120
4        60     70         90
5        60    110        130
6        75    113        133
7        45    116        136
8        45    100        120
9        62     70         90
Dataframe info
<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Duration   10 non-null     int64
 1   pulse      10 non-null     int64
 2   max_pulse  10 non-null     int64
dtypes: int64(3)
memory usage: 320.0+ bytes
None